<?php

namespace Akira\LaravelCrypto;

use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class LaravelCryptoServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        $package
            ->name('laravel-crypto')
            ->hasConfigFile();
    }
    
    public function boot()
    {
        $this->app->singleton(LaravelCrypto::class, function ($app) {
            return new LaravelCrypto(config('crypto'));
        });
        return parent::boot(); // TODO: Change the autogenerated stub
    }
}
